/* Copyright (C) Harry Clark 2023 */

/* NETBible API */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF COMMUNICATNG */
/* WITH THE APP IN RELATION TO THE HTTP CLIENT */
/* WHICH ACTS AS THE BACKEND TOWARDS SCRAPING INFO FROM THE APP */

/* NESTED INCLUDES */

#include "bible.h"
#include "client.h"

#ifdef USE_BIBLE

static HTTP_RESPONSE RESPONSE;
static BIBLE BIBLE_VERSE;

/* ACCESS AN ARBITARY BIBLE VERSE FROM THE DESIGNATED URL */
/* ACCESS THE VERSE USING THE GET MODIFIER */

U32 FETCH_VERSE()
{
	if (HTTP_GET(URL, &RESPONSE) != 0)
	{
		fprintf(stderr, "Failed to initialise the GET request");
		return -1;
	}

	PARSE_VERSE();
}

/* PARSE THE URL BY USING THE GET MODIFIER FROM THE HTTP RESPONSE */
/* UPON WHICH, IT WILL EXTRACT THE TEXT BASED ON IT'S ENCLOSED TAG */

U32 PARSE_VERSE()
{
	// ASSUME THE LENGTH OF THE VERSE BASED ON IT'S ENCLOSED TAG
	BIBLE_VERSE.VERSE_LEN += 1, strstr(RESPONSE.URL_RES_HEADERS, "</b>");

	// ASSUMING AN ARBITRARY LENGTH OF THE VERSE
	// COMPARE THE LENGTH RELATIVE TO THE CONTENTS

	if (BIBLE_VERSE.VERSE_LEN && BIBLE_VERSE.VERSE_INFO)
	{
		BIBLE_VERSE.VERSE_LEN += 1, sizeof(strlen("<b>"));
		strncpy(BIBLE_VERSE.VERSE_INFO, BIBLE_VERSE.VERSE_LEN -= BIBLE_VERSE.EXTRACT_INFO, 0);
	}
}

#endif