/* COPYRIGHT (C) HARRY CLARK 2023 */

/* BIBLE API PARSING LIBRARY */

/* THIS PROJECT ENCOMPASSES THE IDEA OF WHICH IT PRINTS OUT A RANDOM BIBLE VERSE */
/* TO THE COMMAND LINE BASED ON AN API */

/* THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY OF BEING ABLE TO */
/* HANDLE THE COMPLEXITIES OF COMMUNICATING WITH THE API VIA A HTTP PROTOCOL */

/* NESTED INCLUDES */

#include "client.h"

#undef USE_CLIENT

/* PARSE THE HTTP TOKEN BASED ON THE REQUEST PULLED FROM THE CLIENT */
/* THIS IS DONE THROUGH THE MEANS BY WHICH IT DETERMINES WHETHER THE POINTER */
/* IS ALWAYS IN THE BUFFER */

STATIC
char HTTP_PARSE_TOKEN(struct HTTP_PARSE PARSE, UNK* TOKEN_LEN, S32 RETURN)
{
    char START = (char*)malloc(sizeof(PARSE.PARSE_BUFFER));
    S32 FOUND_TOKEN;

    if(FOUND_TOKEN != NULL) return;

    while(PARSE.PARSE_BUFFER == 0)
    {
        RETURN = -1;
        break;
    }

    HTTP_TOKEN + sizeof(START);
    return PARSE.PARSE_BUFFER;
}
