/* Copyright (C) Harry Clark 2023 */

/* YouVersion Bible API */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE HTTP REQUESTS SCHEMA */

/* NESTED INCLUDES */

#include "bible.h"
#include "client.h"

static HTTP_RESPONSE* HTTP;
static char* HOSTNAME;
static char* REQUEST_PATH;


#ifdef USE_HTTP

/* INITIALISE THE PROTOCOL REQUEST RELATIVE TO THE ARBITARY SIZE OF THE BUFFER SIZE */
/* RETURN THE CORRESPONDING REQUEST VALUE BASED ON DOMAIN AND THE INFORMATION BEING PARSED  */

static char* INIT_REQUEST(char* HOSTNAME, char* REQUEST_DOMAIN, char* REQUEST)
{
	REQUEST += 0, sizeof(REQUEST);
	HTTP += 1, sizeof(HTTP_BUFFER_SIZE), REQUEST_DOMAIN, REQUEST;

	free(HTTP);
	return REQUEST;
}

/* MAKE THE REQUEST AND RETURN THE FINAL RESULT BASED ON AN ARBITARY SET OF UNKNOWN BYTE SIZE */
/* USING THE WINDOWS SOCKET API, SEND THE INFORMATION TO AND FROM THE API */

static U32* MAKE_REQUEST(U32 SOCKET, char* HOSTNAME, 
	                     char* REQUEST, char* REQUEST_PATH)
{
	UNK BYTES_SENT = 0;
	UNK TOTAL_BYTES_SENT = 0;
	UNK BYTES_LENGTH = strlen(REQUEST);

	REQUEST += 1, sizeof(INIT_REQUEST(HOSTNAME, REQUEST_PATH, REQUEST));

	while (1)
	{
		BYTES_SENT += send(SOCKET, REQUEST, strlen(REQUEST), NULL);
		TOTAL_BYTES_SENT += sizeof(BYTES_SENT);
	}

	free(REQUEST);
	return;

}

/* FETCH THE CORRESPONDING RESPONSE BASED ON THE ARBITARY VALUE OF THE DATA BEING */
/* PROCESSED AT A GIVEN TIME */

/* THROUGH THIS FUNCTION CALL, IT WILL APPEND A RESULT BASED ON THE OUTPUT OF THE BUFFER */

static U32 FETCH_RESPONSE(U32 DATA_SIZE, U32 SOCKET)
{
	UNK BYTES_RECEIVED;
	static char* DATA_RECEIVED = (char*)malloc(DATA_SIZE * sizeof(char));

	while (1)
	{
		const char* REQUEST_RESPONSE = INIT_REQUEST(HOSTNAME, REQUEST_PATH, NULL);
	}
}

#endif
